### ISSUE TITLE
Fix Google login button

### ISSUE THREAD

**Issue by mrharpo** [WGBH-MLA/ov-wag#139]
```[tasklist]
### Tasks
- [x] Fix / Remove Google button
- [x] Remove unnecessary login redirect
- [x] Fix registration process
```
