### ISSUE TITLE
Footnotes

### ISSUE THREAD

**Issue by mrharpo** [WGBH-MLA/ov-wag#155]
```[tasklist]
### Tasks
- [x] Research https://github.com/torchbox/wagtail-footnotes
- [x] Implement backend
- [ ] https://github.com/WGBH-MLA/ov-wag/pull/156
- [ ] https://github.com/WGBH-MLA/ov-frontend/issues/40
- [ ] Deploy
```
