### ISSUE TITLE
Milestone: Open Vault Launch

### ISSUE THREAD

**Issue by singlesoliloquy** [WGBH-MLA/ov-wag#73]
### Tasks
- [x] https://github.com/WGBH-MLA/ov-deploy/issues/47
- [x] https://github.com/WGBH-MLA/ov-wag/issues/87
- [x] https://github.com/WGBH-MLA/ov-wag/issues/89
- [x] https://github.com/WGBH-MLA/ov-deploy/issues/48
- [x] https://github.com/WGBH-MLA/ov-wag/issues/95
- [x] Add domain to google analytics

**Comment by singlesoliloquy** [comment]
Yay!!!!

**Comment by mrharpo** [comment]
Thanks for getting us started @singlesoliloquy !! 🥳
