### ISSUE TITLE
Migrate to PDM

### ISSUE THREAD

**Issue by mrharpo** [WGBH-MLA/ov-wag#75]
Use PDM for package management.
```[tasklist]
### Tasks
- [x] Create `pyproject.toml`
- [ ] Setup venv defaults
- [ ] Upgrade dependencies
- [ ] https://github.com/WGBH-MLA/ov-wag/issues/79
```
