### ISSUE TITLE
API Authentication

### ISSUE THREAD

**Issue by mrharpo** [WGBH-MLA/ov-wag#90]
# Authentication
Add Auth0 Authentication for API access
```[tasklist]
### Tasks
- [ ] Create Auth0 API: OpenVault
- [ ] Create permissions
- [ ] Create Frontend machine-to-machine  application
- [ ] Apply permissions to Frontend
- [ ] Use `CLIENT_ID` and `CLIENT_SECRET` to create token
- [ ] Refresh process for token
- [ ] Use token in Auth headers
- [ ] Verify token in backend
```

**Comment by jillpe** [comment]
closed, no longer needed
