### ISSUE TITLE
OIDC Authentication

### ISSUE THREAD

**Issue by mrharpo** [WGBH-MLA/ov-wag#91]
# OIDC
Authenticate users using OIDC (Auth0)
```[tasklist]
### Tasks
- [x] Add https://github.com/pennersr/django-allauth
- [x] Create Auth0 Regular Web Application: OpenVault
- [x] Configure secrets
- [ ] https://github.com/WGBH-MLA/ov-wag/pull/132
- [ ] https://github.com/WGBH-MLA/ov-wag/issues/139
```
